services:
  - type: web
    name: tsulovpn
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && python app.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: BOT_NAME
        value: TsuloVPN
      - key: SUBSCRIPTION_PUBLIC_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: PRIMARY_SUB_URL
        value: "https://sub.lidervpn.com/4vpN9ZJGg-hBnfmT"
      - key: WIFI_SOURCE_URLS
        value: "https://sub.lidervpn.com/4vpN9ZJGg-hBnfmT"
      - key: LTE_SOURCE_URLS
        value: "https://sub.lidervpn.com/4vpN9ZJGg-hBnfmT"
      - key: SUBSCRIPTION_CONFIG_LIMIT
        value: "50"
      - key: LTE_CONFIG_LIMIT
        value: "50"
      - key: LTE_BALANCER_NODES
        value: "10"
      - key: KEEP_SOURCE_NAMES
        value: "true"
      - key: SUB_FETCH_UA
        value: "Happ/3.5.0"
      - key: SUB_HWID
        value: "TsuloVPN-Server-Render-01"
      - key: SUB_DEVICE_OS
        value: "Linux"
      - key: SUB_DEVICE_OS_VER
        value: "6.1"
      - key: SUB_DEVICE_MODEL
        value: "TsuloVPN-Server"
      - key: WHITELIST_CIDR_URL
        value: "https://raw.githubusercontent.com/hxehex/russia-mobile-internet-whitelist/main/cidrwhitelist.txt"
      - key: POOL_REFRESH_INTERVAL
        value: "300"
      - key: HAPP_ENCRYPT_SUBSCRIPTION
        value: "true"
      - key: PAYMENTS_ENFORCE
        value: "false"
      - key: SUPPORT_URL
        value: "https://t.me/tsuloew"
      - key: INSTAGRAM_URL
        value: "https://www.instagram.com/tsulo.it"
      - key: DONATE_CARD
        value: "2202209226540747"
      - key: DONATE_CARD_NAME
        value: "АЛИ Ц"
      - key: DONATE_BANK
        value: "Сбербанк"
      - key: PYTHON_VERSION
        value: "3.12.8"
